### ISSUE TITLE
Zip file is invalid - can't open after downloading

### ISSUE THREAD

**Issue by nodrogl** [Esri/arcgis-python-api#1037]
**Describe the bug**
https://github.com/Esri/arcgis-python-api/releases/tag/v1.8.5/source code.zip appears to be inavlid,

Can't open file after downloading

**Platform (please complete the following information):**
 - OS: Windows 8
 - Browser chrome

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by CMPeng** [comment]
Hi @nodrogl I cannot repro the issue you reported here. Since the zipped file is 1.02 GB, and the unzipped folder is 1.41 GB, you might want to check if you have enough space on memory and disk, and/or if you have set an upper limit for the size downloaded files in your Chrome.
BTW. the 1.9.0 release is out, so if the 1.8.5 downloads still failed for you - please try https://github.com/Esri/arcgis-python-api/releases/tag/v1.9
