### ISSUE TITLE
Please document statistic_filter on FeatureLayer.query on the Python API documentation

### ISSUE THREAD

**Issue by crackernutter** [Esri/arcgis-python-api#1199]
The function signature for FeatureLayer query on the Python API documentation lists **statistic_filter** as a parameter, nut there is no associated description or documentation on how to construct the argument, what format is should be in, etc. etc.  I am hoping this has to do with the REST API's "having clause", but need to know how to construct the parameter.  
Thanks!

**Comment by CMPeng** [comment]
Hi @crackernutter Thanks for reporting the issue. We apologize for the missing doc and detailed info about the `statistic_filter` parameter. We will work on adding doc to this parameter (and other similar params) for next release. For the  current being, we will explain some sample usages here:
1. query(..., `statistic_filter=None`, ...) applies to [FeatureLayer](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html?highlight=query#featurelayer) or [Table](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html?highlight=query#arcgis.features.Table.query) objects. Particularly, if there are 1+ sublayers inside a Feature Service, we will need to create the FeatureLayer object with one of the sublayers, 
e.g. `fl = FeatureLayer(url="https://services7.arcgis.com/JEwYeAy2cc8qOe3o/arcgis/rest/services/homicide_USA_07_to_17/FeatureServer/0")`
2. This parameter supports one of the three types of queries: attribute, spatial, and `statistic queries`. Rather than return individual features from a query, you can return statistics for field attributes and expressions. Statistic queries are defined by the [outStatistics](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-Query.html#outStatistics) parameter, which requires an array of [StatisticDefinition](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-StatisticDefinition.html) objects.
 For example, you can query for the average and total population of counties in a country population layer. Ref: [Javascript help doc](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-Query.html#statistic)
The so-called `outStatistics` parameter in Javascript API is equivalent to the `statistic_filter` in Python API.
3. Now, let's look at two use cases in REST API and Python API together:
 - I have published a Feature Service [here](https://geosaurus.maps.arcgis.com/home/item.html?id=9a522a55733a4ff3832988688e994f0f#overview) that displays homicide data from 50 U.S. cities between 2007 and 2017. The data was gathered and analyzed by [The Washington Post]((https://www.washingtonpost.com/graphics/2018/investigations/unsolved-homicide-database/)
 - The rest call to show a total of homecides reported from 2007 to 2017 will be like this - 
 https://services7.arcgis.com/JEwYeAy2cc8qOe3o/ArcGIS/rest/services/homicide_USA_07_to_17/FeatureServer/0/query/wsdl?where=1%3D1&outStatistics=%5B%7B%0D%0A++++onStatisticField%3A+%221%22%2C%0D%0A++++outStatisticFieldName%3A+%22total%22%2C%0D%0A++++statisticType%3A+%22count%22%0D%0A%7D%5D&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=html&token=s3L9aYZBSv5SqZwzwEqgc2UM6nZxHQgueTK_nfIMRCiQ6F30oWetZ5xhj74KBLohy8T4L4js5Wh971at7LxSKOOh8OwD59M5B6LFWQjZHub6jr242g5Dz0KojI_FFt4NiwXwe1R-KYezKsgDcUpyJUe4gw5KlnVKNxhCA0s1etwc4ZJJ8O0hlm4ewf0amdkrGICh1M3S-Dd23grqOPB7IFUALnBlftcf6g1ikHcW-eJpu7ePshpjC0min2y5Sf6m
which will return 

<html>
<body>


total: | 52179
-- | --


<br class="Apple-interchange-newline">
</body>
</html>

 - The rest call to show a total of homecides reported from 2007 to 2017, and the figures classified by open/closed_with_arrest/closed_without_arrest will be like this - https://services7.arcgis.com/JEwYeAy2cc8qOe3o/ArcGIS/rest/services/homicide_USA_07_to_17/FeatureServer/0/query?where=1%3D1&outStatistics=%5B%7B%0D%0A++++onStatisticField%3A+%221%22%2C%0D%0A++++outStatisticFieldName%3A+%22total%22%2C%0D%0A++++statisticType%3A+%22count%22%0D%0A%7D%2C%0D%0A+%7B%0D%0A++++onStatisticField%3A+%22CASE+WHEN+disposition+%3D+%27Closed+by+arrest%27+THEN+1+ELSE+0+END%22%2C%0D%0A++++outStatisticFieldName%3A+%22num_closed_arrest%22%2C%0D%0A++++statisticType%3A+%22sum%22%0D%0A++%7D%2C%0D%0A++%7B%0D%0A++++onStatisticField%3A+%22CASE+WHEN+disposition+%3D+%27Open%2FNo+arrest%27+THEN+1+ELSE+0+END%22%2C%0D%0A++++outStatisticFieldName%3A+%22num_open%22%2C%0D%0A++++statisticType%3A+%22sum%22%0D%0A++%7D%2C%0D%0A++%7B%0D%0A++++onStatisticField%3A+%22CASE+WHEN+disposition+%3D+%27Closed+without+arrest%27+THEN+1+ELSE+0+END%22%2C%0D%0A++++outStatisticFieldName%3A+%22num_closed_no_arrest%22%2C%0D%0A++++statisticType%3A+%22sum%22%0D%0A++%7D%5D&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=html&token=???
 which returns a result like this -

<html>
<body>


total: | 52179
-- | --
num_closed_arrest: | 25674
num_open: | 23583
num_closed_no_arrest: | 2922

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by CMPeng** [comment]
And the equivalent python codes can be found here:
```
from arcgis.gis import GIS
gis = GIS("https://www.arcgis.com", "your_username", "your_password", verify_cert=True)

from arcgis.features import FeatureLayer
fl = FeatureLayer(url="https://services7.arcgis.com/JEwYeAy2cc8qOe3o/arcgis/rest/services/homicide_USA_07_to_17/FeatureServer/0")
fl.query??

# For the 1st use case
stats = [{
    'onStatisticField': "1",
    'outStatisticFieldName': "total",
    'statisticType': "count"
}]
fl.query(statistic_filter=stats)

# for the 2nd use case
stats_all = [{
    'onStatisticField': "1",
    'outStatisticFieldName': "total",
    'statisticType': "count"
  },
 {
    'onStatisticField': "CASE WHEN disposition = 'Closed by arrest' THEN 1 ELSE 0 END",
    'outStatisticFieldName': "num_closed_arrest",
    'statisticType': "sum"
  },
  {
    'onStatisticField': "CASE WHEN disposition = 'Open/No arrest' THEN 1 ELSE 0 END",
    'outStatisticFieldName': "num_open",
    'statisticType': "sum"
  },
  {
    'onStatisticField': "CASE WHEN disposition = 'Closed without arrest' THEN 1 ELSE 0 END",
    'outStatisticFieldName': "num_closed_no_arrest",
    'statisticType': "sum"
  }]
fl.query(statistic_filter=stats_all)
```

**Comment by CMPeng** [comment]
Performing `fl.query??` will print out signature (shown below), and we can see the types required by these parameters here:
```
Signature:
fl.query(
    where: 'str' = '1=1',
    out_fields: 'Union[str, list[str]]' = '*',
    time_filter: 'Optional[list[datetime]]' = None,
    geometry_filter: 'Optional[GeometryFilter]' = None,
    return_geometry: 'bool' = True,
    return_count_only: 'bool' = False,
    return_ids_only: 'bool' = False,
    return_distinct_values: 'bool' = False,
    return_extent_only: 'bool' = False,
    `group_by_fields_for_statistics: 'Optional[str]' = None,`
    `statistic_filter: 'Optional[StatisticFilter]' = None,`
    result_offset: 'Optional[int]' = None,
    result_record_count: 'Optional[int]' = None,
    object_ids: 'Optional[list[str]]' = None,
    distance: 'Optional[int]' = None,
    units: 'Optional[str]' = None,
    max_allowable_offset: 'Optional[int]' = None,
    out_sr: 'Optional[Union[dict[str, int], str]]' = None,
    geometry_precision: 'Optional[int]' = None,
    gdb_version: 'Optional[str]' = None,
    order_by_fields: 'Optional[str]' = None,
    `out_statistics: 'Optional[list[dict[str, Any]]]' = None,`
    return_z: 'bool' = False,
    return_m: 'bool' = False,
    multipatch_option: 'tuple' = None,
    quantization_parameters: 'Optional[dict[str, Any]]' = None,
    return_centroid: 'bool' = False,
    return_all_records: 'bool' = True,
    result_type: 'Optional[str]' = None,
    historic_moment: 'Optional[Union[int, datetime]]' = None,
    sql_format: 'Optional[str]' = None,
    return_true_curves: 'bool' = False,
    return_exceeded_limit_features: 'Optional[bool]' = None,
    as_df: 'bool' = False,
    datum_transformation: 'Optional[Union[int, dict[str, Any]]]' = None,
    **kwargs,
)
```

**Comment by crackernutter** [comment]
Thanks for the explanation! 

So it seems like the parameter out_statistics and statistic_filter can ultimately achieve the same thing.  out_statistics is just structured similarly to the actual REST POST request parameter, where as statistic_filter is an object you construct and pass in to the query method in the Python API.  

That's good to know.  Is there a plan to add support for the "having" parameter?  You can currently pass that in with a POST request natively, but no sure how to do this using the Python API.

**Comment by CMPeng** [comment]
> Thanks for the explanation!
> 
> So it seems like the parameter out_statistics and statistic_filter can ultimately achieve the same thing. out_statistics is just structured similarly to the actual REST POST request parameter, where as statistic_filter is an object you construct and pass in to the query method in the Python API.
> 
> That's good to know. Is there a plan to add support for the "having" parameter? You can currently pass that in with a POST request natively, but no sure how to do this using the Python API.

Hi @crackernutter the documentation is updated. Please check the lastest API Ref and guides. Thanks!
