### ISSUE TITLE
Spatially Enabled Dataframe - edit_features null integers uploading as 0s

### ISSUE THREAD

**Issue by GeeFernando** [Esri/arcgis-python-api#1358]
**Describe the bug**
pd.NA or np.nan values upload as 0s against integer fields (hosted tables and hosted feature layers - with null enabled).

**To Reproduce**

```python
from arcgis.gis import GIS
gis = GIS("home")

import pandas as pd

nullDF = pd.DataFrame({
  "nullString": [pd.NA],
  "nullInteger": [pd.NA],
  "nullDouble": [pd.NA]  
})

# Add 'nulDF' to AGOL table
nullFeatureSet = nullDF.spatial.to_featureset()
nullTableToEdit = gis.content.get("8966b5e40197499fa296a02950d11b6c").tables[0]
nullTableToEdit.edit_features(adds = nullFeatureSet)
```

error:

Link to the resulting hosted table (publicly shared with editing enabled for test purposes) - **https://actgov.maps.arcgis.com/home/item.html?id=8966b5e40197499fa296a02950d11b6c#data**

**Expected behavior**
The integer field should be "null" or "" similar to the `string` or double `fields`.

**Platform**

 - AGOL Notebok Standard and Advanced Runtimes
 - MacOS ArcGIS Python api 2.0.1

**Comment by nanaeaubry** [comment]
Thank you for bringing this up.

I don't think I understand your issue correctly so please correct me if I am wrong: you would like the empty fields in the integer column to be emtpy strings instead of 0?

If this is the case it is not possible because a column's values must all be of the same type. If you have items in the integer column that are `int` values then the nulls will show as 0.

**Comment by GeeFernando** [comment]
> Thank you for bringing this up.
> 
> I don't think I understand your issue correctly so please correct me if I am wrong: you would like the empty fields in the integer column to be emtpy strings instead of 0?
> 
> If this is the case it is not possible because a column's values must all be of the same type. If you have items in the integer column that are `int` values then the nulls will show as 0.

Sorry I wasn't clear in my explanation. `pd.NA` or `np.nan` values get ingested as null values against `string` and `double` fields in hosted tables/layers in ArcGIS Online. But when these values are ingested against an `integer` field, they are recorded as `0`s.

Currently my workflow for ingesting nulls into an integer field is to - initially ingest them as an obviously wrong number (e.g. 9999999). Afterwards, run an Arcade field calculation on the hosted table/layer to covert them to nulls.

It would be great - if a fix could be implemented so `pd.NA` or `np.nan` values get ingested as `nulls` similar to string or double fields.
**Or provide a workaround for ingesting nulls into an integer field 🙏**

Thanks so much 🙏
Gee

**Comment by nanaeaubry** [comment]
@GeeFernando I understand better now thank you for taking the time to explain! Ok I will look into it and let you know if we find a workaround or a fix 👍🏻

**Comment by hildermesmedeiros** [comment]
![image](https://user-images.githubusercontent.com/20046591/197025855-445872dd-62f6-40a4-8501-f7985921aed0.png)
![image](https://user-images.githubusercontent.com/20046591/197026036-5741c68d-5d97-4752-ba6a-3ebb41eac56a.png)

While they don't fix it for you You can do this workflow.

**Comment by GeeFernando** [comment]
> ![image](https://user-images.githubusercontent.com/20046591/197025855-445872dd-62f6-40a4-8501-f7985921aed0.png) ![image](https://user-images.githubusercontent.com/20046591/197026036-5741c68d-5d97-4752-ba6a-3ebb41eac56a.png)
> 
> While they don't fix it for you You can do this workflow.
> 
> @GeeFernando Just a hint, you cant cast np.nan to int32 or int64...... But you can force the request to receive no data, sending an empty string.

Thanks so much for looking into this. Unfortunately, this method doesn't works for me.
I tried both `updating` _(updating existing features)_ and `adding` _(adding new features)_.

But, I do recall this method worked with a previous ArcGIS Python API version.

**Comment by hildermesmedeiros** [comment]
You should Always handle int with extra care, first numpy does not suport casting nan to int. I mean 2010 they started arguing about int supporting nan, and here we are, long history short...you can't do this conversion yet...  

It should fail , your column would be object type if int and nan are in there.
> df.colum.astype('int32') #this is numpy


Howerver we can do it in Pandas.
> df.column.astype('Int32') #Pandas type

If you don't care about performace you could use pandas int type, since they suport nan and the column would be:

https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html
[Int8Dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Int8Dtype.html#pandas.Int8Dtype)
[Int16Dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Int16Dtype.html#pandas.Int16Dtype)
[Int32Dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Int32Dtype.html#pandas.Int32Dtype)
[Int64Dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Int64Dtype.html#pandas.Int64Dtype)
https://github.com/pandas-dev/pandas/blob/v1.5.1/pandas/core/arrays/integer.py#L174-L177


A field length propertie and type propertie would help you with pandas to arcgis type maping. I could have a object pandas column but in gdb, table i want it to be int....so your developers would go extra crazy trying to fix without a clue.

**Comment by nanaeaubry** [comment]
The issue has been fixed for the next version
