### ISSUE TITLE
to_featurelayer with overwrite capability from spatial dataframe

### ISSUE THREAD

**Issue by swilson2023** [Esri/arcgis-python-api#1477]
Hi,

I'm attempting to overwrite a feature layer in arcgis online from python using the to_featurelayer method defined in the following:

https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html

I have a spatial dataframe and am able to create the feature layer without issue, but when I pass overwrite=True and the service parameter, as in the example above, I'm getting an error that the parameters provided to the to_featurelayer method are invalid/unexpected.  I'm confused as the documentation indicates that these parameters can be provided as optional arguments. 

I'm wondering if I'm simply passing these parameters incorrectly, lacking the appropriate version of the arcgis api, or something else.

Thank you and best regards,
Sam

**Comment by swilson2023** [comment]
Just to add - the specific issue I'm running into is the following:

I have a spatially enabled dataframe, like so:

sedf = pd.DataFrame.spatial.from_xy(df, 'lon', 'lat')

When I run sedf.spatial.to_featurelayer without the overwrite=True and service arguments, it successfully creates a new feature layer in arcgis online.  However, when I pass overwrite=True and service arguments, to the to_featurelayer method, it returns the following error, which seems inconsistent with the documentation (unless I'm doing it wrong!):

TypeError: to_featurelayer() got an unexpected keyword argument 'overwrite'

Thanks in advance for any help you can provide.

Best,
Sam

**Comment by nanaeaubry** [comment]
Hello can you please provide some more complete code on how you are passing everything in this way we can test it on our end?

Thanks!

**Comment by nanaeaubry** [comment]
@swilson2023 

Awesome thanks for the explanation. So the error you are getting it making me think you are not at the most recent version of the API. We added overwrite at version 2.1.0 (current version is 2.1.0.2). 
So I would try updating the version you are using.

Second thing is that for the `service` parameter make sure you are passing in the layer id as well:
```
service = {“featureServiceId” : “9311d21a9a2047d19c0faaebd6f2cca6”, “layer”: 0}
```
You have to specify the layer that will be overwritten since your feature service could contain more than one layer. If you only have one layer just go ahead and pass in 0 like the example above.

Hope this helps! Let me know if this fixes your issue

**Comment by swilson2023** [comment]
Bingo.. the version update worked - thanks so much!

**Comment by nanaeaubry** [comment]
Awesome! Closing this issue then :)

**Comment by swilson2023** [comment]
Thanks again!
