### ISSUE TITLE
QUESTION - loop list of "Fixes" when updating attributes

### ISSUE THREAD

**Issue by SPhillips2022** [Esri/arcgis-python-api#1513]
In my code below, I am manually entering fixes but I would rather feed it a list of needed fixes - any help would be appreciated:

ALL_fl = item.layers[0]
FIX = ("ENERTECH INDUSTRIES")
fix_features = [f for f in ALL_fset if f.attributes["MNFRS_3S"] == FIX]
edits = []

for feature in fix_features:
    feature.attributes["MNFRS_3S"] = "ENERTECH"
    edits.append(feature)

update_result = ALL_fl.edit_features(updates=edits)
print(update_result)

**Comment by SPhillips2022** [comment]
I do have the query setting creating ALL_fset - missed copying it here.

**Comment by nanaeaubry** [comment]
Just to make sure I understand correctly,
You are feeding in a list of the fixes but instead you want to feed in the fix itself and it does it automatically?

If this is the case it is not possible since we would not know what attribute to feed it to or to how many of the attributes, because sometimes a user just wants to fix one of the cases.

**Comment by nanaeaubry** [comment]
You would have to do your data transformation outside of the the method as you are doing now and you can do some looping along with if statements to make sure you are correcting the correct attribute to what you want it to be
