### ISSUE TITLE
Download an export without name parameter and the name is modified

### ISSUE THREAD

**Issue by gdherbert** [Esri/arcgis-python-api#1563]
**Describe the bug**
When downloading an export (such as a fgdb) using the API and not providing a file name, the name will have underscores removed. It appears that underscores are scrubbed.

**To Reproduce**
```python
item = gis.content.get('83616500ccc14026ad36de5025d06daa') #example item
result = item.export(title='This_should_be_a_valid_name', export_format='File Geodatabase', overwrite=True) # create export package
result.download(save_path='C:\\Temp')
```

**Expected behavior**
Downloaded file would be named 'This_should_be_a_valid_name' instead it is named 'Thisshouldbeavalidname'
Providing a file_name works as expected. 

```
result.download(save_path=output_location, file_name='This_works.zip')
```

**Platform (please complete the following information):**
 - OS: Windows
 - Python API Version 2.1.0.2

**Comment by nanaeaubry** [comment]
Thanks for reporting, we will take a look

**Comment by nanaeaubry** [comment]
Just FYI, your export method is wrong, it cannot accept the parameter overwrite. 

I cannot reproduce your issue. When I run this code I get a download path with the intended file name:
```
item = gis.content.get("de5b947226ae4a67a94aa65cac9e20ff")
result = item.export(title='This_should_be_a_valid_name', export_format='File Geodatabase')
result.download()
```

result: 'C:\\Users\\nan\\AppData\\Local\\Temp\\1\\This_should_be_a_valid_name.zip'

**Comment by nanaeaubry** [comment]
So I have done the same:
![image](https://github.com/Esri/arcgis-python-api/assets/19919283/d4a3bec7-1662-4887-af03-29b8cf0d29d7)

It works on my end and I get the correct name, however I noticed in the code that if there is an error downloading the item it will log an error and then retry by parsing the file name. It seems there is an error occurring on your end for some reason and that's why the title gets reformatted. If you can attempt to debug or get the log of errors you can see why this is failing for you.

There are three calls this can be failing at: 1. get data from the item 2. Extracting the data 3. Handling the download response and getting the path that was created.

Otherwise the behavior is as expected.

Since this is occurring on your end I would assume it has something to do with the data itself, we cannot do more on our end, sorry! Hope this is able to provide a bit of guidance for debugging
