### ISSUE TITLE
Reason why ArcGIS API for python doesnot support latest version of Python

### ISSUE THREAD

**Issue by Sindhuits** [Esri/arcgis-python-api#1595]
Hi,

I have installed latest version of Python and did a pip install arcgis. I was not able to connect to GIS. But when I downgraded the Python version to python-3.9.13.exe it worked. May i know the reason why ArcGIS API for python doesnot support latest version of Python?

**Comment by nanaeaubry** [comment]
Hello,

Due to dependency issues we have to make many changes when supporting the newest python versions. At our next release we will support newer versions. 
It's just a matter of guaranteeing everything will still work if we upgrade, this is the same reason for other libraries as well.

Hope that answers your question
