### ISSUE TITLE
Overwriting Hosted Table in Online Capabilities

### ISSUE THREAD

**Issue by kphaneuf** [Esri/arcgis-python-api#1774]
When turning off editing capabilities, overwrite worked in GUI but not API.

```
csv_properties={"title":"FLTest"}
csv_item = r"C:\Users\kphaneuf\Documents\FLTest.csv"

# table = gis.content.add(item_properties=csv_properties, data=csv_item)
# analyzed = gis.content.analyze(item=table)
# pp = analyzed['publishParameters']
# pp['name'] = 'MyTable'
# pp['locationType'] = None
# item= table.publish(pp)
flayer_collection = FeatureLayerCollection.fromitem(item)
# print(flayer_collection)
#print(csv_item)


#flayer_collection.manager.update_definition(params)
flayer_collection.manager.overwrite(csv_item)
```
![image](https://github.com/Esri/arcgis-python-api/assets/13141791/8e82acb2-e7ce-40a4-aa85-9dab398037f3)

**Comment by nanaeaubry** [comment]
Extra comment: 
```
params = {"capabilities": "Query,Editing,Create,Update,Delete",
    "layerOverridesEnabled": True,}
```

updating the definition with this works but removing and having just Query is not working. Normally this was as expected but it seems online no longer blocks the capability even though we do.

Need to mess with it online

**Comment by nanaeaubry** [comment]
@kphaneuf Can you post the small csv we had used?

**Comment by kphaneuf** [comment]
[FLTest.csv](https://github.com/Esri/arcgis-python-api/files/14620629/FLTest.csv)

Sure, here you go.

**Comment by nanaeaubry** [comment]
@kphaneuf 

Ok I was able to test this better and found a few things. First of all you can just pass `{"locationType" : None}` to the publish method and it will create the table. So no need for the analyze step.

Second, the front end seems to have a bug. When we turn off editing capabilities, it shows that you can still overwrite and when you overwrite you get a little green popup at the bottom of the screen saying overwrite was successful. But this is wrong! If we look at the network traffic we see that success was actually False:

![image](https://github.com/Esri/arcgis-python-api/assets/19919283/ae3afc3b-fd90-482a-97ea-af8b83a11d38)

So the necessity to set the capabilities to "Query, Editing,...." as we had seen is actually needed. I will report this bug to online since the ability to overwrite is not available without them.

So just to conclude:
the workflow we found where to define the capabilities, do an update_defintion with the FeatureLayerCollectionManager, overwrite the service, and then set back the capabilities to just "Query" is the best workflow and the correct way to do it.

Hope all of this helps, Ill close the issue since it is resolved and alert online about it but feel free to comment more if needed. Thanks!
