### ISSUE TITLE
update function for webmap doesn't work (but no error is given)

### ISSUE THREAD

**Issue by artsmax** [Esri/arcgis-python-api#1839]
**Describe the bug**
I am trying to update a webmap (webmap2) with the all the content,symbology etc from another webmap (webmap1).
When I use the update function with the definition of webmap1, True is returned, while webmap2 isn't changed at all

**To Reproduce**
![image](https://github.com/Esri/arcgis-python-api/assets/125013101/758cb45d-6f19-41a7-ac89-0ce476af679f)

**Expected behavior**
An updated webmap containing same layers, symbology etc as the reference webmap

**Platform (please complete the following information):**
 - Python API Version 2.2.0

**Comment by nanaeaubry** [comment]
@artsmax 
There is no key "text" in the item properties that allows you to do this. I will try to find you a workflow and post it here

**Comment by artsmax** [comment]
thank you for your reply. In the end I want to update a webmap based on a json file, so saving it as a new one doesnt do the trick in my case. I'm looking forward to your workflow!

**Comment by artsmax** [comment]
@nanaeaubry , I would still like to see your workflow:) Are you able/willing to share? regards, Max

**Comment by nanaeaubry** [comment]
@artsmax 
Thanks for being patient! I got the update to work but have a few caviats to make you aware of as well.

Here is the code:

```
from arcgis.gis import GIS
from arcgis.mapping import WebMap
import json
gis = GIS(profile="your_online_profile")

# Get the two webmap items we want to use
item1 = gis.content.get("fa14b6470a8845aca963051e57c2f4bb")
item2 = gis.content.get("6093ff378f2546bea2159ab7beae0569")


# Use the data from symbol_webmap to update the basic_webmap
data = item2.get_data()
item1.update({"text":json.dumps(data)})
item1
```

You were on the right track to use the json data of the item and pass as text. However, the update should be done on the Item class and not the WebMap class. In the Item class we accept 'text' as a key in the item_properties dictionary.

This will work BUT it depends on your use case. I tested this where I had a feature layer in two different webmaps. In one webmap I left it as-is and in another I updated the symbology and saved it. Then when I did the update above the basic webmap got updated with the cool symbology. 
This will work if you have the same feature layers in your webmap. This will not work if you have different feature layers and you want to apply the symbology of one layer to a totally different layer. 
The reason is that the underlying structures are dictionaries. So this is a dictionary updating another dictionary and the rules for that apply. You might have to do a bit of manual search and replace if you want to apply to more complicated use cases.

Hope this helps jump start what you are trying to do! :) Good luck!

**Comment by artsmax** [comment]
thank you very much! Exactly what I was looking for:)
