### ISSUE TITLE
Jupyter Lab

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#184]
Any idea on whether the API will work with JupyterLab?

**Comment by wiringa** [comment]
The code in the your first notebook sample seemed OK up until map display. Displaying `map1` did not work in JupyterLab for me. It did work in Jupyter Notebook running in the same environment.

> Widget Javascript not detected.  It may not be installed or enabled properly.

**Comment by DavidJVitale** [comment]
Hi @guyn2gis @wiringa,

Since Jupyterlab is still in beta, we have no immediate plans to support the API's use in it. The map display functionality is implemented using Jupyter __notebook__'s `ipywidget` and `nbextension` system, whereas JupyterLab uses a different (and still changing) extension system. This is why you cannot see the map draw.

Other aspects of the API besides map drawing might work OK in Jupyterlab.

**Comment by rohitgeo** [comment]
Thank you for letting us know about your interest in JupyterLab. There is a dev project underway to provide updated widgets for use in JupyterLab. You can expect the widgets to work by the time JupyterLab comes out of beta.

**Comment by DavidJVitale** [comment]
v1.5.0 of the ArcGIS API for Python is live with JupyterLab support! Here is the main guide page for it at the moment: https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/

After installing v1.5.0, you need to run the following two commands to get the widget activated: the above guide outlines these steps as well:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install arcgis-map-ipywidget@1.5.0
```

Feel free to report a new issue with any comments you may have: Hope you enjoy using JupyterLab :)
