### ISSUE TITLE
arcgis package not getting installed on azure function app

### ISSUE THREAD

**Issue by sheetallomate** [Esri/arcgis-python-api#1873]
We have an ArcGIS PRO version installed in an Azure VM. We need to call the arcgis network find routes from an azure function app. We have private endpoint network established between VM hosting https://sandboxesrivm01.fqdn.com/portal and azure function app where we would be calling that instance. When we are trying to deploy azure function including  arcgis python sdk package via requirements.txt . 
•	this fails the deployment as it is getting stuck at pip install step for arcgis
•	we came across similar issue reported at ESRI community site... [Deploying function App to azure stuck on 'running ... - Esri Community](https://community.esri.com/t5/arcgis-api-for-python-questions/deploying-function-app-to-azure-stuck-on-running/td-p/1482555)

The code we are trying to call from the azure function app (running of EP1 plan based on linux and Python 3.10 version) is as below to create the GIS object

my_gis = GIS("https://sandboxesrivm01.fqdn.com/portal","admin","password")
my_gis

We are following this link: https://developers.arcgis.com/python/guide/part2-find-routes/ 
and need to use network.analysis.find_routes method.

**Comment by jtroe** [comment]
We currently have support for ArcGIS Python API on AWS Lambda.  In order to facilitate this, we had to use their containerized infrastructure (Docker images).  I suspect this will be the case for Azure Functions also.

Here is the Azure Functions documentation on using a Docker image to back the Function: https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container-apps?tabs=acr%2Cbash&pivots=programming-language-csharp#create-and-configure-a-function-app-on-azure-with-the-image

The AWS Lambda base image we supply is here: https://github.com/Esri/arcgis-python-api/pkgs/container/arcgis-python-api-lambda and the Dockerfile used to generate it is here: https://github.com/Esri/arcgis-python-api/blob/master/docker/LambdaBaseImage.Dockerfile

I will investigate the feasibility of building a base image with the ArcGIS API for Python preinstalled that you can inherit from to develop your solution.

**Comment by jtroe** [comment]
@sheetallomate Please see https://github.com/Esri/arcgis-python-api/blob/master/docker/README.md#azurefunctionsbaseimage for instructions on getting started with the image I've hosted.
