### ISSUE TITLE
Notebook URL Link is broken

### ISSUE THREAD

**Issue by HigginTown** [Esri/arcgis-python-api#198]
arcgis-python-api/samples/05_content_publishers/overwriting_feature_layers.ipynb

First URL link is broken here

https://github.com/Esri/arcgis-python-api/blob/ff4b347a43b7061ea1132ecc8619249eb419a42b/samples/05_content_publishers/python/sample-notebooks/updating-features-in-a-feature-layer/

also here

https://github.com/Esri/arcgis-python-api/blob/master/guide/04-feature-data-and-analysis/features-module.ipynb

under `Getting familiar with features module`

Thanks for the great content! Loved the Esri Dev Summit!!!!

**Comment by rohitgeo** [comment]
Thanks for reporting this @HigginTown.

The link works fine when this notebook is published to the developers website at https://developers.arcgis.com/python/guide/features-module/

However, I see the problem that when it's rendered using GitHub, the links cannot be followed. Any ideas on how we could fix this @AtmaMani ? One option might be to link to the developers website instead using the full url instead of a relative url - i.e. https://developers.arcgis.com/python/guide/editing-features/

**Comment by AtmaMani** [comment]
@rohitgeo Yes, @DavidJVitale is planning to update notebooks here to use absolute links. We will switch them to relative when publishing via CI system.
