### ISSUE TITLE
Update PIP install topic with more details

### ISSUE THREAD

**Issue by khibma** [Esri/arcgis-python-api#201]
This section: https://developers.arcgis.com/python/guide/install-and-set-up/#Install-using-pip explains that you can PIP install `arcgis`

I ran into some troubles when attempting to PIP install. Perhaps relevant details could be added to the doc to make it more clear.

1.  `pip install arcgis --no-deps` results in an error like:

> distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I do not have VS Build tools installed. However, doing a `pip install setuptools --upgrade` allows me to install. I believe I went from v20-something to v39.

2.  After setuptools upgrade, I recieved the following error while attempting to install. (I was using the built in Python from Pro 2.0.1). You can see it fails as it tries to load arcpy.

>       File "c:\program files\arcgis\pro\Resources\ArcPy\arcpy\__init__.py", line  66, in <module>
>         from arcpy.geoprocessing import gp
>       File "c:\program files\arcgis\pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14, in <module>
>         from ._base import *
>       File "c:\program files\arcgis\pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 14, in <module>
>         import arcgisscripting
>     RuntimeError: Not signed into Portal.

3. I installed Python 3.5 stand alone (moving away from the builtin Python), then updated setuptools, then was able to do a `pip install arcgis --no-deps`  successfully. When attempting to `import arcgis` I received an error about **six** not installed. After `pip install six` I was able to successfully import arcgis.  So it seems six isn't really an optional dependency.

**Comment by DavidJVitale** [comment]
Hi @khibma, thanks for your issue, it is appreciated.

1. This is a known issue with the pip installer, and should be fixed by our next release. Thanks for reporting it.
2. When you use the "builtin Python from Pro 2.0.1", you are using the anaconda distribution with pro. Anaconda includes a pip executable, which is probably what you are running (It can be confusing I know). The `Not Signed into Portal` error is because the API is attempting to import `arcpy`. `arcpy` must be licensed for use, and it looks like the installer couldn't authenticate through Portal. Read more about it here: https://gis.stackexchange.com/questions/238985/avoiding-arcgisscripting-runtimeerror-not-signed-into-portal-from-arcpy-with-ar
3. `six` is the only true 'dependency' of the API, as it is required on the system even for a simple `import arcgis`. All other 'dependencies' are just if you want to use specific functionality of the API. This is documented here: https://developers.arcgis.com/python/guide/system-requirements/

**Comment by DavidJVitale** [comment]
Hi @khibma , we are releasing v1.4.1 by the end of next week. In that fix, `pip install arcgis --no-deps` will work without Visual C++ tools. You still may need C++ tools for a standard install: for some of our dependencies, it will attempt to install a wheel of that dependency. If it can't find one, it will compile one with Visual C++ tools. So it depends on if you can find a wheel in your environment.

I have addressed your concerns with comments 2) and 3), let me know if you have any other concerns.
