### ISSUE TITLE
documentation on moving from spatialdataframe

### ISSUE THREAD

**Issue by Dan-Patterson** [Esri/arcgis-python-api#315]
There is a reference to a warning in Line 221 of 
C:\ .... \bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\_data\geodataset\geodataframe.py
 

> #warnings.warn("SpatialDataFrame has been deprecated. 
> Please switch to the GeoAccessor/GeoSeriesAccessor.")
> 

 
It appears that a pandas dataframe and series are now a substitute?  (for example, the *.py scripts in  
C:\ArcGISPro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\geo )

Is there any documentation on this?   Also, since numpy object arrays are supported natively with FeatureClassToNumPyArray and its siblings, what was the reason to wrap some of the basic array functions into Pandas-ish classes rather than provide direct, or even twin, functionality with numpy?  A simple example is using ExtendTable to join.  Any insights would be useful.  
Do you have plans to enable subclassing for other array-like objects other than Pandas 'arrays' ?

**Comment by achapkowski** [comment]
@Dan-Patterson we do not have a migration guide in place to go from an SDF to an SeDF.  I will look into that.  We switched from the inheritance model to the accessor pattern because that is what was recommended by the Pandas' Developer Team.  I wanted to ensure best practices are followed.  Inheritance, though great part of OO, in this case causes major issues with Panda's DataFrames and Series core functionality.  You can see this on other projects that use this model as well.  With the release of pandas v.23, the development team introduce custom namespaces or accessors.  It allows for the Pandas' logic to remain unchanged, while injecting new functionality.  

The new functionality:

1. Geometry Dtype (in SpatialDataFrame Geometries were Objects)
2. Series namespace called `geom` on `GeoArrays` (geometry dtype).  This works on rows or single values
3. DataFrame namespace called `spatial` which allows for dataset wide operations.  You can get things like extent, spatial reference, geometry type, etc..

Does  this help?

I've looked at extending `xarray` and `dask`, but nothing that it is release worthy besides Pandas.

If I were to use `da.ExtendTable`, I would do the following (off the top of my head):

```python

index = [1, 2, 3, 4, 5, 6, 7]
a = [np.nan, np.nan, np.nan, 0.1, 0.1, 0.1, 0.1]
b = [0.2, np.nan, 0.2, 0.2, 0.2, np.nan, np.nan]
c = [np.nan, 0.5, 0.5, np.nan, 0.5, 0.5, np.nan]
df = pd.DataFrame({'A': a, 'B': b, 'C': c}, index=index)
df = df.rename_axis('ID')
array = df.reset_index().values.ravel().view(dtype=[('index', int), ('A', float), ('B', float), ('C', float)])
# You can probably also use df.as_matrix() or df.values as well to get your np.array.
#... do da.ExtendTable or FeatureClassToNumpyArray 

```

Numpy is great, but pandas, IMHO, has a better interface.  In general `numpy` tends to  be used for numerical analysis of data. In general, `pandas` tends to be data gathering and subsequent data wrangling.  It is also a community favorite for data science and ML/AI, etc....

**Comment by Dan-Patterson** [comment]
Maybe I am more familiar with numpy than most, so it does provide a friendlier appearance I will grant you that, but I have no problem working with it.  The converting from/to featureclasses could easily accept structured/recarrays without having to throw the pandas cloak over it.  I do this all the time when working with the geometry or the attribute portion.  Even adding the ability to read numpy npy, npz directly would be nice (pickle objects and not csv format).  

The existing FeatureClassToNumPyArray and back, TableToNumPyArray and back and RasterToNumPyArray and back are great access points to-from numpy for geometry, attributes and raster data, I was just looking for a more direct way of getting that data read used without having to go through pandas.  As long as these don't get deprecated, I will just avoid the pandas bloat since I work mostly with vector geometry (hence numpy and arcpy) and rasters stacks

**Comment by achapkowski** [comment]
Going out of one's comfort zone is always difficult.  Pandas is widely accepts as a good data structure and has many application across the landscape.

What `bloat` are you referring to?

**Comment by Dan-Patterson** [comment]
I have to laugh at the 'comfort zone' comment.  We will leave it there and I will document elsewhere.

**Comment by achapkowski** [comment]
Sounds good, I just wanted to also say I do enjoy reading your blog posts about coding, general insights and analysis.

**Comment by Dan-Patterson** [comment]
Just finished one ;).  
Regards Dan
