### ISSUE TITLE
spatial_join "df1 must be a spatial dataframe"

### ISSUE THREAD

**Issue by akochman** [Esri/arcgis-python-api#674]
**Describe the bug**
I have two spatially enabled dataframes sdf1 and sdf2.
sdf1 = GeoAccessor.from_xy(df, x_column = 'ftEasting', y_column = 'ftNorthing', sr=2228)
sdf2 = GeoAccessor.from_featureclass(flora_pres_burn_area)

sdf1 are points from a SQL query, brought into a pandas dataframe with df = pd.read_sql_query(query, con=engine) then converted into sdf1 using GeoAccessor.from_xy

sdf2 is just taken from a feature class in an SDE.

Both show .info() as <class 'pandas.core.frame.DataFrame'>

When from arcgis.features import SpatialDataFrame sdf_join1 = spatial_join(sdf1, sdf2) is ran, an error shows stating "ValueError: df1 must be a spatial dataframe"

**To Reproduce**
1. Create sdf1 from a pandas dataframe using GeoAccessor.from_xy
2. Create sdf2 from a feature class on a local gdb or sde
3. Run sdf_join1 = spatial_join(sdf1, sdf2)

*I've also split out as df1=sdf1, df2=sdf2 with same bug

error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-8c9fa7e52f77> in <module>
      1 from arcgis.features import SpatialDataFrame
      2 
----> 3 sdf_join1 = spatial_join(sdf1, sdf2)

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\_data\geodataset\tools.py in spatial_join(df1, df2, left_tag, right_tag, keep_all)
     22     from arcgis.features import SpatialDataFrame
     23     if not isinstance(df1, SpatialDataFrame):
---> 24         raise ValueError("df1 must be a spatial dataframe")
     25     if not isinstance(df2, SpatialDataFrame):
     26         raise ValueError("df2 must be a spatial dataframe")

ValueError: df1 must be a spatial dataframe

**Screenshots**
![image](https://user-images.githubusercontent.com/18711565/79394618-ccd4ad00-7f2c-11ea-8cad-278571976a74.png)

**Expected behavior**
Spatial join to perform as documented in https://developers.arcgis.com/python/guide/advanced-topics/

**Platform (please complete the following information):**
 - OS: Windows (On AWS EC2)
 - Browser Firefox
 - Python API Version 1.7.1

**Additional context**
I can complete a spatial join in ArcGIS Pro and ArcMap when the sdf1 is exported out as a feature class. I'll most likely end up using arcpy to complete the spatial join until this bug is worked out or resolved.

**Comment by priyankatuteja** [comment]
Hi @akochman Can you provide the two data frames you are trying to join, need those to reproduce it.

**Comment by achapkowski** [comment]
What happens if you do a df1.spatial.name and df2.spatial.name?

Do you get an output for each?

**Comment by akochman** [comment]
@priyankatuteja I'm creating some dummy data right now in sdf1test and sdf2test. Dropping csv's of them in the zip.

@achapkowski the output of sdf1.spatial.name and sdf2.spatial.name is 'SHAPE'. sdf1test and sdf2test just had the same error.

![image](https://user-images.githubusercontent.com/18711565/79481586-9185bd00-7fc4-11ea-9249-b3521be3efb0.png)
![image](https://user-images.githubusercontent.com/18711565/79483464-330e0e00-7fc7-11ea-9c19-2639517881c8.png)

[sdftests.zip](https://github.com/Esri/arcgis-python-api/files/4488588/sdftests.zip)

**Comment by priyankatuteja** [comment]
@akochman It is interesting to see that the df1 you shared, has invalid geometry. To confirm if 
`GeoAccessor.from_xy(df1, "ftEasting", "ftNorthing", sr=2228)` worked fine for you. I dropped the  'SHAPE' column and re-ran the command to create a spatially enabled data frame similar to df1 you shared. 
It turns out that I am able to make it spatial with valid geometry. See image below: 
![image](https://user-images.githubusercontent.com/39754605/79556291-7f884500-80be-11ea-9127-4bc669c68e8e.png)
 
I found likewise df2 geometry is invalid. If you could share a zip file of featureClass you used to convert into the dataframe. I can check if that again works at my end.  

Moreover, https://developers.arcgis.com/python/guide/advanced-topics/ link explains how to do spatial join. In the last section, you will find df1.spatial.join(df2) is how we expect it to run. 
`from arcgis.features._data.geodataset.tools import spatial_join` is not how you should be trying as once the reason is it's not a publicly exposed method another reason is the SpatialDataFrame method is now deprecated.

**Comment by akochman** [comment]
Hi @priyankatuteja 
Sorry for the delay, it seems the sdf1.spatial.join(sdf2) works for me now.
I believe the issue was linked to using the deprecated method.

Thank you for pointing me to this updated guide.
