### ISSUE TITLE
Problem With Accessing GIS Python Playground?

### ISSUE THREAD

**Issue by ZhiliWang** [Esri/arcgis-python-api#687]
Hi. I am researching a topic that can really benefit from this sample: https://developers.arcgis.com/python/sample-notebooks/identifying-suitable-sites-for-als-clinics-using-location-allocation-analysis/

I tried to run the following line both locally and your "Try It Live", and both platforms generated similar errors:

```python
<gis = arcgis.GIS('https://python.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')>
```
error from Live:
```python
<

ConnectionError: A connection error has occurred: HTTPSConnectionPool(host='python.playground.esri.com', port=443): Max retries exceeded with url: /portal/sharing/rest/info?f=json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f07ba9576d8>: Failed to establish a new connection: [Errno 110] Connection timed out'))
>
```

error from Local:
```python
<
ConnectionError: A connection error has occurred: HTTPSConnectionPool(host='python.playground.esri.com', port=443): Max retries exceeded with url: /portal/sharing/rest/info?f=json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbc93a73a0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
>
```

**Platform (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Jupyter Notebook on Chrome
 - Python API Version: 1.8.0`

Thank you!

**Comment by achapkowski** [comment]
Do you have a proxy that you failed to define or do you have internet access on the machine you are calling this from?

**Comment by achapkowski** [comment]
We have update the Try It Live feature.  Please try again.

**Comment by akochman** [comment]
This issue is happening again regardless of environment.

`gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123', set_active=False)`

ERROR:;

ConnectionError: A connection error has occurred: HTTPSConnectionPool(host='ip-172-31-29-237.us-east-2.compute.internal', port=443): Max retries exceeded with url: /portal/sharing/rest/generateToken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F1EB6B0148>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
