### ISSUE TITLE
[Question] How is the ArcGIS library licensed?

### ISSUE THREAD

**Issue by johnclary** [Esri/arcgis-python-api#801]
The [`arcgis` package](https://pypi.org/project/arcgis/) on pypi.org has a proprietary license that redirects to [https://www.esri.com/en-us/legal/overview](https://www.esri.com/en-us/legal/overview).

There are a lot of documents to navigate there. Can you point us to the terms of use that apply to this library?

**Comment by Dan-Patterson** [comment]
According to the licensing at the bottom of this page...
https://github.com/Esri/arcgis-python-api
You don't get to use arcpy unless you have a valid esri software license, otherwise everything geometry, that can be emulated is largely done through shapely.  
try anaconda through the esri site
https://anaconda.org/esri/arcgis

**Comment by AtmaMani** [comment]
@johnclary This repo (SDK notebooks and API ref files) are available under [Apache 2.0](https://github.com/Esri/arcgis-python-api/blob/master/LICENSE). The Python API source code is available under [Esri Master License Agreement](https://www.esri.com/content/dam/esrisites/en-us/media/legal/ma-translations/english.pdf). 

I am copying my product manager (cc @skalisky) if you would like to reach out and talk to someone about this.
