### ISSUE TITLE
CSS issue when running Jupyter in https://

### ISSUE THREAD

**Issue by DruidSmith** [Esri/arcgis-python-api#86]
We are running Jupyter Hub on a server, and the Jupyter url is an https:// url.

When the ArcGIS Python API loads, it runs, but interactive map results don't render properly because the map widget is unable to load the CSS because the python API code references http:// and the browser blocks the mixed content because of the https:// session.

Relevant errors below (with url redacted):

> Mixed Content: The page at 'https://****' was loaded over HTTPS, but requested an insecure stylesheet 'http://js.arcgis.com/3.17/esri/css/esri.css'. This request has been blocked; the content must be served over HTTPS.

> Mixed Content: The page at 'https://****' was loaded over HTTPS, but requested an insecure stylesheet 'http://js.arcgis.com/3.17compact/dijit/themes/claro/claro.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by rohitgeo** [comment]
Thanks for reporting this. We've fixed this internally and the fix will be included in the next update. Till then, you can use the workaround of editing custom.css and using the lines below:

@import url("//js.arcgis.com/3.17/esri/css/esri.css");
@import url("//js.arcgis.com/3.17compact/dijit/themes/claro/claro.css");

instead of 

@import url("http://js.arcgis.com/3.17/esri/css/esri.css");
@import url("http://js.arcgis.com/3.17compact/dijit/themes/claro/claro.css");

You'd have to find and change custom.css where it's deployed on your server. It's included in the arcgis (widget) folder that gets deployed to the nbextensions directory.

**Comment by DruidSmith** [comment]
Great, thanks for the quick response Rohit.  Will give it a shot.

David G. Smith PE PLS
USEPA Office of Environmental Information – OEI / OIM / IAASD
202.566.0797| http://epa.gov/enviro |

**Comment by DruidSmith** [comment]
This interim fix has been working great for us.  Thanks again Rohit.
