### ISSUE TITLE
1912 bad links in the python doc 

### ISSUE THREAD

**Issue by isaacviel** [Esri/arcgis-python-api#930]
**Describe the bug**
1912 bad links across the https://developers.arcgis.com/python/ section

**To Reproduce**
See https://link-checker.afd.geocloud.com/#prod#python

error:
4xx

**Expected behavior**
Users and search engines should find all links working as expected.

@AtmaMani and team, we really need to get the bulk of these link fixes prioritized as we're receiving a lot of negative feedback for bad links from partners and users. This many bad links will also have negative consequences in search results.

**Comment by jyaistMap** [comment]
hey @isaacviel
 * we're looking into this and some PRs will be coming up soon to address many of the bad links

**Comment by isaacviel** [comment]
Thanks @jyaistMap!

**Comment by isaacviel** [comment]
Just noticed today's run of the link checker now shows 3639 errors for Python after yesterday's release so be sure to check out the newest data. 

Thanks!

**Comment by priyankatuteja** [comment]
@isaacviel The bad links are mainly because of the following reasons:
1. the api reference page earlier had a different link. Recently, the learn module has been reorganized and a toc is added hence the links are changed from https://developers.arcgis.com/python/api-reference/arcgis.learn.html to https://developers.arcgis.com/python/api-reference/arcgis.learn.toc.html
2. our guides do not provide data along but for visualization of how things will come up, there are dummy items shown throughout all modules of python api guides. it is expected for those items to be invalid.
3. the samples which have a workflow that runs multiple tools and creates items, won't be available since geosaurus org is designed in a way that all the items provided via arcgis_python username gets deleted every other day. 
cc  @AtmaMani @jyaistMap

**Comment by jyaistMap** [comment]
@isaacviel 
  * the number appears larger than direct impact in that any bad link on any API Reference page is reported for each release:
![image](https://user-images.githubusercontent.com/1399179/113614851-ea9c9580-9607-11eb-85c8-98da35301016.png)
    * is there any way the report can skip bad links from previous releases?
  * to add onto @priyankatuteja's point in bullet 2 above, many bad links are reported from thumbnails resulting from display output, so they are not links that a consumer of the page would be directed to use

**Comment by isaacviel** [comment]
@jyaistMap We can add past releases to the "do not check" list as a last resort if it's not possible to fix the links and republish?

**Comment by jyaistMap** [comment]
@isaacviel  That sounds like a good plan.

**Comment by jyaistMap** [comment]
Closing this - team is dealing it with issue internally: [#7853](https://github.com/ArcGIS/geosaurus/issues/7853)
